server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    
    # LA LÍNEA MÁGICA: El buscador es el corazón de la app
    index search.html; 

    include /etc/nginx/mime.types;

    location /login {
        try_files /login.html =404;
    }

    location /register {
        try_files /register.html =404;
    }

    location / {
        try_files $uri $uri/ /search.html;
    }
}