server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    
    index search.html; 

    include /etc/nginx/mime.types;

    location /login {
        try_files /login.html =404;
    }

    location /register {
        try_files /register.html =404;
    }

    location / {
        try_files $uri $uri/ /search.html;
    }

    location /premium {
        try_files /premium.html =404;
    }
}