apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kali/Desktop/pruebask8s/search/data/postgres"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-db-dep
spec:
  selector:
    matchLabels:
      app: search-db
  template:
    metadata:
      labels:
        app: search-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "kubeflix123"
        - name: POSTGRES_DB
          value: "search_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: search-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: search-db-storage
        persistentVolumeClaim:
          claimName: search-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: search-db-service
spec:
  selector:
    app: search-db
  ports:
    - port: 5432